'use strict';(function(){var cmpFile='noModule'in HTMLScriptElement.prototype?'cmp2.js':'cmp2-polyfilled.js';(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpUrl;var tagUrl=document.currentScript.src;cmpUrl='https://cmp.inmobi.com/tcfv2/53/CMP_FILE?referer=cryptobriefing.com'.replace('CMP_FILE',cmpFile);cmpScriptElement.src=cmpUrl;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #368bd6 !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #368bd6 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';var gvlVersion=2;function splitLang(lang){if(lang.includes('pt')&&lang.length>2){return lang.split('-')[0]+'-'+lang.split('-')[1].toLowerCase();}
return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','pt-br','pt-pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','uk','zh','id','ko','ja','hi','vi','th','ms'];return langs.indexOf(lang)===-1?false:true;};if(gvlVersion===2&&isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(gvlVersion===3&&isSupported(document.documentElement.lang)){autoDetectedLanguage=document.documentElement.lang;}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{"coreConfig":{"uspVersion":1,"uspJurisdiction":["CA"],"uspLspact":"N","siteUuid":"86ef4c75-18ec-46d8-92ca-857e78499eb8","themeUuid":"6ddb7887-4775-4210-9ae6-628a180620b2","inmobiAccountId":"nwS18F5XLGdW_","privacyMode":["GDPR","USP"],"includeVendorsDisclosedSegment":false,"cmpVersion":"53","hashCode":"HNLMl4WLMv5Dbo0jbbDbdA","publisherCountryCode":"US","publisherName":"Crypto Briefing","vendorPurposeIds":[1,2,3,4,5,6,7,8,9,10],"vendorFeaturesIds":[1,2,3],"vendorPurposeLegitimateInterestIds":[2,3,4,5,6,7,8,9,10],"vendorSpecialFeaturesIds":[1,2],"vendorSpecialPurposesIds":[1,2],"googleEnabled":true,"consentScope":"service","thirdPartyStorageType":"iframe","consentOnSafari":false,"displayUi":"inEU","softOptInEnabled":false,"showSummaryView":true,"persistentConsentLinkLocation":3,"uiLayout":"popup","publisherLogo":"https://static.cryptobriefing.com/wp-content/uploads/2019/11/02093657/Logo-2x.png?qc-size=574,154","vendorListUpdateFreq":30,"publisherPurposeIds":[],"initScreenBodyTextOption":1,"publisherConsentRestrictionIds":[],"publisherLIRestrictionIds":[],"publisherPurposeLegitimateInterestIds":[],"publisherSpecialPurposesIds":[],"publisherFeaturesIds":[],"publisherSpecialFeaturesIds":[],"stacks":[1,42],"lang_":"en","gvlVersion":2,"legitimateInterestOptIn":true,"features":{"visitEvents":true},"translationUrls":{"common":"https://cmp.inmobi.com/tcfv2/translations/${language}.json","theme":"https://cmp.inmobi.com/custom-translations/inmobi/6ddb7887-4775-4210-9ae6-628a180620b2/${language}.json","all":"https://cmp.inmobi.com/consolidated-translations/inmobi/6ddb7887-4775-4210-9ae6-628a180620b2/${language}.json"},"gdprEnabledInUS":false},"premiumUiLabels":{},"premiumProperties":{"googleWhitelist":[1]},"coreUiLabels":{},"theme":{},"nonIabVendorsInfo":{"nonIabVendorList":[{"vendorId":1,"pCode":"nwS18F5XLGdW_","name":"Nexo","description":"Nexo is the premier wealth platform for digital assets.","privacyPolicyUrl":"https://nexo.com/terms?id=privacy-policy","nonIabPurposeConsentIds":[1,2,3,4,7],"nonIabPurposeLegitimateInterestIds":[],"active":null}]}});})();